### ISSUE TITLE
Performance enhancements for Media polling

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#329]
This is dependent on a new feature of baw-workers (https://github.com/QutBioacoustics/baw-workers/issues/54).

# Proposal

Simplify polling for media creation by using the blobs stored in Redis (new feature in https://github.com/QutBioacoustics/baw-workers/issues/54), in live generation scenarios, rather than retrieve the file from disk/NFS mount. This change should increase performance and actually simplify our code.

# Work items

For retrieving pre-generated media, we still do the standard disk check to return cache files. This issue is for optimising the live generation path.

- [ ] Ensure web server checks for Redis blob first (using the expected media file name), and then checks disk caches
- [ ] Remove live-generation disk polling
- [ ] Change live-generation redis polling to check for key with name of expected media file name
- [ ] If media blob found in redis, serve result to HTTP response (
- [ ] Consider failure scenarios (TTL race conditions, race conditions with keys, Redis downtime)
- [ ] Write unit tests

# Related conversations

- https://github.com/QutBioacoustics/baw-private/issues/141
- https://github.com/QutBioacoustics/baw-private/issues/43
- https://github.com/QutBioacoustics/baw-workers/issues/54

**Comment by atruskie** [comment]
Closed by #f11c39b2e84e9e80838492435d0c788c9a245539
