### ISSUE TITLE
New site_photos feature

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/baw-server#373]
This issue supersedes #303, #315, and #110.

# Motivation

@proe, @lizznidersic, and several other users have expressed a desire to store more photographic assets along with audio data. There are three cases:

- One or many high-resolution images stored per site
- The possibility of storing [spherical images from a site](https://developers.google.com/streetview/spherical-metadata)
- Storing a stream of photos from the site (as captured by a camera trap)

# Tasks

- [ ] Create a database table to store metadata for these images
- [ ] Ensure images can be created and deleted
- [ ] Consider storage backends for the images.

# Notes

Note this issue will not include any UI. We're mainly interested in storing the images for now and we'll expose the UI in the client later.

Open questions:
- Which storage backend will we use? (Disk, SQLite, a cloud BLOB service)?
- PaperClip is deprecated. Should we move to Rail's own Active Storage? Or leverage our existing media infrastructure and build our own?
- What information do we need to capture?
- Will there ever only be one camera trap at a site?
- Should the harvester ingest these photos?

Proposed schema (a cheap knock-off of `audio_recordings`):
```sql
CREATE TABLE site_photos (
    id integer NOT NULL,
    uuid character varying(36) NOT NULL,
    uploader_id integer NOT NULL,
    recorded_date timestamp without time zone NOT NULL,
    site_id integer NOT NULL,
    type varchar NOT NULL,
    media_type character varying NOT NULL,
    data_length_bytes bigint NOT NULL,
    file_hash character varying(524) NOT NULL,
    status character varying DEFAULT 'new'::character varying,
    notes text,
    creator_id integer NOT NULL,
    updater_id integer,
    deleter_id integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    original_file_name character varying,
    recorded_utc_offset character varying(20)
);
```
