### ISSUE TITLE
[TRACKING] Cms page bugs/issues

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#500]
Tracking the list of incorrect links and broken formatting in the cms pages so they can be fixed:

- Data Upload:
  - [ ] Why is this now called Data Upload? It was Send Audio in previous versions
  - [ ] Contact us link path is broken (multiple)
  - [ ] Audio recordings table is not mobile compatible. Needs to be wrapped so that the table does not extend outside the page width, and instead can be scrolled horizontally
- Disclaimers:
  - [ ] Contact us link path is broken
- Credits
  - [ ] Confusing use of links for [Queensland University of Technology’s](https://www.qut.edu.au/) and [Ecoacoustics Research Group](http://research.ecosounds.org/)
  - [ ] Update Programs and libraries to include workbench-client libraries? (ie. Angular, ngx-formly, etc...)
  - [ ] nectar link is broken
- Ethics
  - [ ] Contact us link is broken
- Home
  - [ ] Should the github link point to workbench-client or all repos?

**Comment by atruskie** [comment]
- data upload
    - The page is "send audio". The view fragment that was replaced was called "data_upload" and the name was kept for consistency. The route is also `/data_upload`. I believe the discrepancy was raised during a feedback session and the title "send audio" was deemed clearer
    - See 1.
    - See 2.
- Disclaimers
    - See 1.
- Credits
    - See 2.
    - See cms_seeds.rb, but also, see 2.
    - See 2.
- Ethics:
    - See 1.
- Home
    - See 2. Short answer though is it should point to our org, as it does now.


1. Remember the current cms content is serving live content for the rails site. For the site it is not broken. We'll update the link when the new client is deployed
2. that content is instance specific and is not related to this repo or issue tracker

**Comment by Allcharles** [comment]
>1. Remember the current cms content is serving live content for the rails site. For the site it is not broken. We'll update the link when the new client is deployed

Then this should remain an open issue so that the problems aren't forgotten when we deploy the new client?

> 2. that content is instance specific and is not related to this repo or issue tracker

Where would you like me to track theses cms related issues instead?

**Comment by atruskie** [comment]
> Can we properly clean this up and use a consistent naming scheme? Also, on the website, this is displayed as the "Send Audio" link, however when you access the page the CMS page displays Data Upload. This may cause confusion for users

Url: /data_upload
Name: Send audio

Everything else should be changed via CMS

> Then this should remain an open issue so that the problems aren't forgotten when we deploy the new client?

Maybe. But this issue included a lot of not-relevant noise.

> Where would you like me to track theses cms related issues instead?

Content related to an instance can be fixed using the `/admin/cms` interface for each instance. The baw-private repo could be used for this purpose but I'd suggest just fixing it.

**Comment by Allcharles** [comment]
Contact us links for the deployed service are also broken btw

**Comment by atruskie** [comment]
how?
